language: ruby
rbenv: 
- 2.7.2
cache: 
  - bundler
  - yarn
services: 
  - postgresql
before_install:
  - nvm install --lts
  - gem install bundler -v '2.2.24'
before_script:
  - bundle install
  - yarn
  - bundle exec rake db:create
  - bundle exec rake db:migrate
script: 
  - bundle exec rspec